# frozen_string_literal: true

require_relative '../models'

module EasyPostV5::InternalUtilities::StaticMapper
  BY_PREFIX = {
    'adr' => EasyPostV5::Models::Address,
    'ak' => EasyPostV5::Models::ApiKey,
    'bank' => EasyPostV5::Models::PaymentMethod,
    'batch' => EasyPostV5::Models::Batch,
    'brd' => EasyPostV5::Models::Brand,
    'ca' => EasyPostV5::Models::CarrierAccount,
    'card' => EasyPostV5::Models::PaymentMethod,
    'cstinfo' => EasyPostV5::Models::CustomsInfo,
    'cstitem' => EasyPostV5::Models::CustomsItem,
    'es' => EasyPostV5::Models::EndShipper,
    'evt' => EasyPostV5::Models::Event,
    'hook' => EasyPostV5::Models::Webhook,
    'ins' => EasyPostV5::Models::Insurance,
    'order' => EasyPostV5::Models::Order,
    'payload' => EasyPostV5::Models::Payload,
    'pickup' => EasyPostV5::Models::Pickup,
    'pickuprate' => EasyPostV5::Models::PickupRate,
    'pl' => EasyPostV5::Models::PostageLabel,
    'plrep' => EasyPostV5::Models::Report,
    'prcl' => EasyPostV5::Models::Parcel,
    'rate' => EasyPostV5::Models::Rate,
    'refrep' => EasyPostV5::Models::Report,
    'rfnd' => EasyPostV5::Models::Refund,
    'sf' => EasyPostV5::Models::ScanForm,
    'shp' => EasyPostV5::Models::Shipment,
    'shpinvrep' => EasyPostV5::Models::Report,
    'shprep' => EasyPostV5::Models::Report,
    'trk' => EasyPostV5::Models::Tracker,
    'trkrep' => EasyPostV5::Models::Report,
    'user' => EasyPostV5::Models::User,
  }.freeze

  BY_TYPE = {
    'Address' => EasyPostV5::Models::Address,
    'ApiKey' => EasyPostV5::Models::ApiKey,
    'BankAccount' => EasyPostV5::Models::PaymentMethod,
    'Batch' => EasyPostV5::Models::Batch,
    'Brand' => EasyPostV5::Models::Brand,
    'CarbonOffset' => EasyPostV5::Models::CarbonOffset,
    'CarrierAccount' => EasyPostV5::Models::CarrierAccount,
    'CreditCard' => EasyPostV5::Models::PaymentMethod,
    'CustomsInfo' => EasyPostV5::Models::CustomsInfo,
    'CustomsItem' => EasyPostV5::Models::CustomsItem,
    'EndShipper' => EasyPostV5::Models::EndShipper,
    'Event' => EasyPostV5::Models::Event,
    'Insurance' => EasyPostV5::Models::Insurance,
    'Order' => EasyPostV5::Models::Order,
    'Parcel' => EasyPostV5::Models::Parcel,
    'PaymentLogReport' => EasyPostV5::Models::Report,
    'Pickup' => EasyPostV5::Models::Pickup,
    'PickupRate' => EasyPostV5::Models::PickupRate,
    'PostageLabel' => EasyPostV5::Models::PostageLabel,
    'Rate' => EasyPostV5::Models::Rate,
    'Refund' => EasyPostV5::Models::Refund,
    'RefundReport' => EasyPostV5::Models::Report,
    'Report' => EasyPostV5::Models::Report,
    'ScanForm' => EasyPostV5::Models::ScanForm,
    'Shipment' => EasyPostV5::Models::Shipment,
    'ShipmentInvoiceReport' => EasyPostV5::Models::Report,
    'ShipmentReport' => EasyPostV5::Models::Report,
    'TaxIdentifier' => EasyPostV5::Models::TaxIdentifier,
    'Tracker' => EasyPostV5::Models::Tracker,
    'TrackerReport' => EasyPostV5::Models::Report,
    'User' => EasyPostV5::Models::User,
    'Webhook' => EasyPostV5::Models::Webhook,
  }.freeze
end
